export  const ORDERSLIST_REQUEST = "ORDERSLIST_REQUEST";
export  const ORDERSLIST_SUCCESS = "ORDERSLIST_SUCCESS";
export  const ORDERSLIST_FAIL =  "ORDERSLIST_FAIL";

export const GET_ALL_ORDER_LIST_REQUEST = "GET_ALL_ORDER_LIST_REQUEST";
export const GET_ALL_ORDER_LIST_SUCCESS = "GET_ALL_ORDER_LIST_SUCCESS";
export const GET_ALL_ORDER_LIST_FAIL = "GET_ALL_ORDER_LIST_FAIL";

export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_FAIL = "CART_FAIL";

export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";

export const PLACE_ORDERS_REQUEST = "PLACE_ORDERS_REQUEST";
export const PLACE_ORDERS_SUCCESS = "PLACE_ORDERS_SUCCESS";
export const PLACE_ORDERS_FAIL = "PLACE_ORDERS_FAIL";

export const GET_TICKETS_REQUEST = "GET_TICKETS_REQUEST";
export const GET_TICKETS_SUCCESS = "GET_TICKETS_SUCCESS";
export const GET_TICKETS_FAIL = "GET_TICKETS_FAIL";

export const GET_YOUR_TICKETS_REQUEST = "GET_YOUR_TICKETS_REQUEST";
export const GET_YOUR_TICKETS_SUCCESS = "GET_YOUR_TICKETS_SUCCESS";
export const GET_YOUR_TICKETS_FAIL = "GET_YOUR_TICKETS_FAIL";

export const ACCEPT_ORDER_REQUEST = "ACCEPT_ORDER_REQUEST";
export const ACCEPT_ORDER_SUCCESS = "ACCEPT_ORDER_SUCCESS";
export const ACCEPT_ORDER_FAIL = "ACCEPT_ORDER_FAIL";

export const REJECT_ORDER_REQUEST = "REJECT_ORDER_REQUEST";
export const REJECT_ORDER_SUCCESS = "REJECT_ORDER_SUCCESS";
export const REJECT_ORDER_FAIL = "REJECT_ORDER_FAIL";

export const DELETE_ORDER_REQUEST = "REJECT_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "REJECT_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "REJECT_ORDER_FAIL";

export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAIL = "GET_STATUS_FAIL";

export const EMPTY_CART = "EMPTY_CART";

export const REMOVE_YOUR_REJECTED_TICKETS_REQUEST = "REMOVE_YOUR_REJECTED_TICKETS_REQUEST";
export const REMOVE_YOUR_REJECTED_TICKETS_SUCCESS = "REMOVE_YOUR_REJECTED_TICKETS_SUCCESS";
export const REMOVE_YOUR_REJECTED_TICKETS_FAIL = "REMOVE_YOUR_REJECTED_TICKETS_FAIL";

export const RELEASE_ORDER_REQUEST = "RELEASE_ORDER_REQUEST";
export const RELEASE_ORDER_SUCCESS = "RELEASE_ORDER_SUCCESS";
export const RELEASE_ORDER_FAIL = "RELEASE_ORDER_FAIL";

export const GET_IMAGEPATH_REQUEST = "GET_IMAGEPATH_REQUEST";
export const GET_IMAGEPATH_SUCCESS = "GET_IMAGEPATH_SUCCESS";
export const GET_IMAGEPATH_FAIL = "GET_IMAGEPATH_FAIL";

export const UPDATE_IMAGEPATH_SUCCESS = "UPDATE_IMAGEPATH_SUCCESS";
export const UPDATE_IMAGEPATH_FAIL = "UPDATE_IMAGEPATH_FAIL";

export const DELIVER_SUCCESS_REQUEST = "DELIVER_SUCCESS_REQUEST";
export const DELIVER_SUCCESS_SUCCESS = "DELIVER_SUCCESS_SUCCESS";
export const DELIVER_SUCCESS_FAIL = "DELIVER_SUCCESS_FAIL";
